stages:
  - build-humacs
  - build-ii

variables:
  GIT_SUBMODULE_STRATEGY: recursive

.registry-login: &registry-login |
  cat << EOF > /kaniko/.docker/config.json
  {
    "auths":{
      "$CI_REGISTRY": {
        "username":"$CI_REGISTRY_USER",
        "password":"$CI_REGISTRY_PASSWORD"
      }
    }
  }
  EOF

.declare-extra-destinations: &declare-extra-destinations |
  if [ -n "$CI_COMMIT_TAG" ]; then
    export KANIKO_EXTRA_DESTINATION="--destination $CI_REGISTRY_IMAGE/$REPOSITORY:$CI_COMMIT_TAG"
  fi

.build: &build |
  /kaniko/executor \
    --cache=false \
    --context $CI_PROJECT_DIR \
    --dockerfile $CI_PROJECT_DIR/Dockerfile \
    --destination $CI_REGISTRY_IMAGE/$REPOSITORY:latest \
    $KANIKO_EXTRA_DESTINATION

build-humacs:
  stage: build-humacs
  image:
    name: gcr.io/kaniko-project/executor:debug-v0.13.0
    entrypoint: [""]
  variables:
    REPOSITORY: humacs
  before_script:
    - *registry-login
    - *declare-extra-destinations
  script:
    - *build

build-ii:
  stage: build-ii
  image:
    name: gcr.io/kaniko-project/executor:debug-v0.13.0
    entrypoint: [""]
  variables:
    REPOSITORY: ii
  before_script:
    - *registry-login
    - *declare-extra-destinations
  script:
    - *build
