{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "humacs.serviceAccountName" . }}
  labels:
{{ include "humacs.labels" . | nindent 4 }}
{{- end -}}
